### ISSUE TITLE
goToPage报错

### ISSUE THREAD

**Issue by Mrwangfan** [doterlin/vue-pagination#1]
1、Property or method "goToPage" is not defined on the instance but referenced during render. Make sure to declare reactive data properties in the data option.
（怎么解决）
2、有没有更好的方案 （比如 点击页数， goToPage就是页数+1， 显示在input中，不影响input的输入跳转，） @doterlin

**Comment by doterlin** [comment]
谢谢issues，我暂时没能重现这个bug，请问怎么触发这个bug的，你是什么浏览器呢 @Mrwangfan

**Comment by Mrwangfan** [comment]
1、目前用的是谷歌在做调试 ，  把组件引入就报错，但是不影响功能，然后我在跳转的input 中输入值点击确定， 这个报错就没了 ，但是下载你的 demo 没有这个错
2、还是我之前说的那个（比如点击页数，goToPage就是页数+1，显示在输入中，不影响输入的输入跳转，）
3、还有就是要是我们后台返回的数据格式是这样的 1_8_0_1_不限_不限_0_150_0_200_0_20_0_100000_1_不限_0 第一位是页码 在你写的组件中 怎么用（谢谢！） @doterlin

**Comment by doterlin** [comment]
引入就报错的话可能是你引入的时候出了什么问题。 检查vue.js组件里的data什么的跟template对应上了没

**Comment by Mrwangfan** [comment]
好的 我在调试看看  谢谢

**Comment by Mrwangfan** [comment]
解决了了   是我不仔细 谢谢

**Comment by doterlin** [comment]
不客气

**Comment by perchecc** [comment]
apppagination 和 pagination 组件间报错，出现 The computed property "currentPage" is already defined as a prop。请问怎么解决 @doterlin

**Comment by doterlin** [comment]
可能是vue.js的版本问题，我用的时候是v2.1.6, 这个跑起来没问题https://doterlin.github.io/vue-pagination/
，这个问题算是vue.js的版本兼容问题，我有空处理一下。谢谢提醒！@ackemaneva
